export const mockStudent = {
  id: "stu-001",
  name: "蒋皓博",
  nickname: "蒋皓博",
  age: 10,
  gender: "male",
  class: "PAB U10提高班",
  coach: "王教练",
  avatar: "/students/jiang-haob0.jpg",
  cardPhoto: "/students/jiang-haob0.jpg",
  number: "3",
  namePinyin: "JIANG HAOBO",
  position: "GUARD",
  currentStage: "L2 稳定阶段",
  organization: "PAB球馆",
  joinedAt: "2025-09-01",
};

export const mockBadges = [
  { id: "b1", name: "勇敢突破时刻", description: "在对抗中主动选择突破，展现进攻信心", icon: "🏆", dimension: "心理成长", awardedAt: "2026-05-24" },
  { id: "b2", name: "最佳回防", description: "失误后秒速回防，展现团队责任感", icon: "🛡️", dimension: "比赛状态", awardedAt: "2026-05-10" },
  { id: "b3", name: "传球小达人", description: "主动传球，开始观察队友位置", icon: "🎯", dimension: "团队协作", awardedAt: "2026-04-28" },
  { id: "b4", name: "连续训练达成", description: "连续4周出勤，训练习惯稳定", icon: "⭐", dimension: "训练习惯", awardedAt: "2026-04-15" },
];

export const mockReport = {
  id: "rpt-001",
  studentId: "stu-001",
  sessionId: "sess-001",
  title: "蒋皓博 5月24日比赛成长报告",
  date: "2026-05-24",
  type: "match",
  status: "published",
  heroSummary: "今天最值得记录的，不是得分，而是蒋皓博开始在对抗下主动突破。过去几场他更多是在外线等待机会，但今天有两次主动选择进攻，说明他的比赛信心正在建立。",
  badge: mockBadges[0],
  clips: [
    {
      id: "clip-001",
      title: "勇敢突破",
      dimension: "心理成长",
      tag: "敢于突破",
      level: "L2",
      thumbnail: "/videos/thumb1.jpg",
      videoUrl: "/videos/clip1_breakthrough.mp4",
      parentExplanation: "这次突破虽然没有得分，但蒋皓博主动选择面对防守人，这是很重要的变化。对这个阶段的孩子来说，敢于尝试本身就是成长。",
      coachComment: "主动突破意愿提升，说明训练中的突破动作开始迁移到比赛。下一阶段建议强化左手突破后的终结稳定性。",
      timestamp: "12:34",
    },
    {
      id: "clip-002",
      title: "失误后快速回防",
      dimension: "比赛状态",
      tag: "快速回防",
      level: "L2",
      thumbnail: "/videos/thumb2.jpg",
      videoUrl: "/videos/clip2_defense.mp4",
      parentExplanation: "蒋皓博这次被抢断后没有停在原地，而是马上回防。这说明他正在建立比赛责任感和抗挫力。",
      coachComment: "失误后的转换反应明显提升，建议继续强化攻防转换速度。",
      timestamp: "23:15",
    },
    {
      id: "clip-003",
      title: "主动传球",
      dimension: "团队协作",
      tag: "主动传球",
      level: "L1",
      thumbnail: "/videos/thumb3.jpg",
      videoUrl: "/videos/clip3_passing.mp4",
      parentExplanation: "这次传球说明蒋皓博开始观察队友位置，不只是自己处理球。团队意识正在形成。",
      coachComment: "传球选择比之前更合理，下一步可以训练传球后的继续移动。",
      timestamp: "31:50",
    },
  ],
  progressPoints: [
    "主动进攻意愿增强，有两次主动突破尝试",
    "失误后回防更积极，展现比赛责任感",
    "开始观察队友位置并做出传球选择",
  ],
  improvementPoints: [
    "左手突破后的终结稳定性还在提升中，这是下阶段的练习重点",
    "传球后的二次跑位可以进一步加强，让队友更容易配合",
  ],
  coachAdvice: "建议继续强化左手突破后的终结，并加强传球后的二次跑位训练。保持主动参与比赛的信心，这是目前最重要的成长方向。",
  nextSteps: [
    "继续练习左手突破后的终结",
    "强化传球后的二次跑位",
    "保持主动参与比赛的信心",
  ],
};

export const mockReportRpt002 = {
  id: "rpt-002",
  studentId: "stu-001",
  sessionId: "sess-002",
  title: "蒋皓博 5月10日训练成长记录",
  date: "2026-05-10",
  type: "training",
  status: "published",
  heroSummary: "这次训练最让我印象深刻的，是蒋皓博在防守端的专注。之前他在防守时容易分心，但这次训练里有两次关键的协防补位，说明他开始用大局观打球了。",
  badge: mockBadges[1],
  clips: [
    {
      id: "clip-002-a",
      title: "关键协防补位",
      dimension: "比赛状态",
      tag: "快速回防",
      level: "L2",
      thumbnail: "/videos/thumb2.jpg",
      videoUrl: "/videos/clip2_defense.mp4",
      parentExplanation: "这次协防说明蒋皓博不只在盯自己的人，还在关注整个防守端。这是很重要的防守意识提升，很多成年球员都未必能做到。",
      coachComment: "协防时机判断准确，移动速度也快。下一步可以练习协防后如何快速归位，形成完整的防守轮转。",
      timestamp: "08:22",
    },
    {
      id: "clip-002-b",
      title: "稳定传球出球",
      dimension: "团队协作",
      tag: "主动传球",
      level: "L2",
      thumbnail: "/videos/thumb3.jpg",
      videoUrl: "/videos/clip3_passing.mp4",
      parentExplanation: "训练中的传球比比赛更稳定了，说明他在安全环境下已经建立了这个习惯，下一步就是把它迁移到比赛压力下。",
      coachComment: "传球出手时机越来越果断，不再犹豫。建议继续强化接球即传的节奏，减少多余的运球。",
      timestamp: "19:45",
    },
  ],
  progressPoints: [
    "防守专注度明显提升，有效完成两次协防补位",
    "传球出手更果断，减少了犹豫期",
  ],
  improvementPoints: [
    "协防后的快速归位还需加强，避免给对方留下空位",
    "对抗强度下的传球稳定性仍有提升空间",
  ],
  coachAdvice: "本次训练防守端进步明显，是本周训练的最大亮点。建议下周专项训练协防归位的速度，同时继续在对抗中练习传球节奏。",
  nextSteps: [
    "练习协防后快速归位的脚步",
    "加强对抗中传球的稳定性",
    "巩固防守专注度，延伸到比赛场景",
  ],
};

export const mockReportRpt003 = {
  id: "rpt-003",
  studentId: "stu-001",
  sessionId: "sess-003",
  title: "蒋皓博 4月28日比赛成长报告",
  date: "2026-04-28",
  type: "match",
  status: "published",
  heroSummary: "这场比赛蒋皓博的传球意识有了明显觉醒。他开始不只想着自己处理球，而是主动观察队友位置。虽然最终结果不是每次都完美，但这个改变本身就非常珍贵。",
  badge: mockBadges[2],
  clips: [
    {
      id: "clip-003-a",
      title: "传球创造机会",
      dimension: "团队协作",
      tag: "主动传球",
      level: "L2",
      thumbnail: "/videos/thumb3.jpg",
      videoUrl: "/videos/clip3_passing.mp4",
      parentExplanation: "这次传球是蒋皓博主动观察到队友空位后做出的选择，不是被迫的，而是主动的。这种团队意识在10岁的孩子身上很难得。",
      coachComment: "传球选择非常合理，时机也抓得好。这说明他的比赛视野在拓宽，下一步练习传球后的无球跑动。",
      timestamp: "14:10",
    },
    {
      id: "clip-003-b",
      title: "主动寻找突破",
      dimension: "心理成长",
      tag: "敢于突破",
      level: "L1",
      thumbnail: "/videos/thumb1.jpg",
      videoUrl: "/videos/clip1_breakthrough.mp4",
      parentExplanation: "虽然这次突破被防住了，但蒋皓博主动去尝试的勇气很重要。比赛是练习勇气的最好地方，敢于尝试就是成长。",
      coachComment: "突破意图清晰，但切入路线选择还需要优化。建议继续多尝试，找到自己最顺手的突破角度。",
      timestamp: "27:33",
    },
  ],
  progressPoints: [
    "传球意识觉醒，开始主动观察并为队友创造机会",
    "进攻主动性有所提升，开始尝试突破",
  ],
  improvementPoints: [
    "传球后的二次跑位还未形成习惯，传完球后容易停在原地",
    "突破路线的选择需要更多训练，找到自己的优势方向",
  ],
  coachAdvice: "传球意识的觉醒是这场比赛最大的收获。建议重点强化传球后的继续移动，让团队配合更流畅。同时继续鼓励主动突破的尝试。",
  nextSteps: [
    "练习传球后立即移动，不停在原地",
    "找到自己最顺手的突破路线",
    "保持对全场局势的观察习惯",
  ],
};

export const mockReportRpt004 = {
  id: "rpt-004",
  studentId: "stu-001",
  sessionId: "sess-004",
  title: "蒋皓博 4月15日训练成长记录",
  date: "2026-04-15",
  type: "training",
  status: "published",
  heroSummary: "蒋皓博这四周的出勤率达到了100%，每次训练都全力投入。稳定的训练习惯本身就是一种重要的成长——它意味着他对篮球有了真正的热爱和承诺。",
  badge: mockBadges[3],
  clips: [
    {
      id: "clip-004-a",
      title: "全力对抗不退缩",
      dimension: "心理成长",
      tag: "敢于突破",
      level: "L2",
      thumbnail: "/videos/thumb1.jpg",
      videoUrl: "/videos/clip1_breakthrough.mp4",
      parentExplanation: "连续四周出勤，每次都全力投入训练，这本身就是一种了不起的坚持。这次对抗中的不退缩，正是四周积累的成果。",
      coachComment: "对抗中的投入度和上个月相比有明显提升，身体对抗时不再退缩。这是持续训练带来的自信。建议保持这种势头。",
      timestamp: "31:05",
    },
  ],
  progressPoints: [
    "连续四周100%出勤，训练习惯稳定建立",
    "对抗中的身体投入度明显提升，不再退缩",
  ],
  improvementPoints: [
    "对抗后的体力管理需要加强，避免后半段训练质量下降",
  ],
  coachAdvice: "连续四周的坚持非常棒！这种训练态度是未来进步的基础。建议下阶段在保持出勤的同时，关注训练后半段的体力分配。",
  nextSteps: [
    "保持稳定的出勤习惯",
    "注意训练后半段的体力分配",
    "把训练中的对抗投入度延伸到比赛中",
  ],
};

export const mockReports = [mockReport, mockReportRpt002, mockReportRpt003, mockReportRpt004];

export const mockGrowthHistory = [
  {
    id: "rpt-001",
    date: "2026-05-24",
    type: "match",
    title: "蒋皓博 5月24日比赛成长报告",
    summary: "蒋皓博开始在对抗中主动突破，比赛信心正在建立",
    badge: "勇敢突破时刻",
    clipCount: 3,
  },
  {
    id: "rpt-002",
    date: "2026-05-10",
    type: "training",
    title: "5月10日训练成长记录",
    summary: "防守专注度明显提升，协防补位意识增强",
    badge: "最佳回防",
    clipCount: 2,
  },
  {
    id: "rpt-003",
    date: "2026-04-28",
    type: "match",
    title: "4月28日比赛成长报告",
    summary: "传球意识觉醒，开始主动为队友创造机会",
    badge: "传球小达人",
    clipCount: 2,
  },
  {
    id: "rpt-004",
    date: "2026-04-15",
    type: "training",
    title: "4月15日训练成长记录",
    summary: "连续出勤四周，训练投入度持续稳定",
    badge: "连续训练达成",
    clipCount: 1,
  },
  {
    id: "rpt-005",
    date: "2026-03-28",
    type: "match",
    title: "3月28日比赛成长报告",
    summary: "开始尝试突破，进攻主动性有初步提升",
    badge: null,
    clipCount: 2,
  },
];

export const mockRadarData = [
  { dimension: "技术成长", score: 62, fullMark: 100 },
  { dimension: "战术认知", score: 45, fullMark: 100 },
  { dimension: "比赛状态", score: 70, fullMark: 100 },
  { dimension: "心理成长", score: 75, fullMark: 100 },
  { dimension: "团队协作", score: 55, fullMark: 100 },
  { dimension: "训练习惯", score: 85, fullMark: 100 },
];

export const mockGrowthCurve = [
  { week: "3/1", 技术成长: 45, 心理成长: 50, 团队协作: 40 },
  { week: "3/15", 技术成长: 48, 心理成长: 55, 团队协作: 42 },
  { week: "3/28", 技术成长: 52, 心理成长: 60, 团队协作: 45 },
  { week: "4/15", 技术成长: 55, 心理成长: 65, 团队协作: 50 },
  { week: "4/28", 技术成长: 58, 心理成长: 68, 团队协作: 54 },
  { week: "5/10", 技术成长: 60, 心理成长: 71, 团队协作: 53 },
  { week: "5/24", 技术成长: 62, 心理成长: 75, 团队协作: 55 },
];

export const mockPendingReports = [
  {
    id: "sess-001",
    student: "蒋皓博",
    studentId: "stu-001",
    date: "2026-05-24",
    type: "比赛",
    clipCount: 3,
    status: "awaiting_review",
    aiSummary: "AI已生成3个成长片段，包含突破、回防、传球场景",
  },
  {
    id: "sess-002",
    student: "季禹澄",
    studentId: "stu-002",
    date: "2026-05-24",
    type: "比赛",
    clipCount: 2,
    status: "awaiting_review",
    aiSummary: "AI已生成2个成长片段，包含防守和投篮场景",
  },
  {
    id: "sess-003",
    student: "小杰",
    studentId: "stu-003",
    date: "2026-05-22",
    type: "训练",
    clipCount: 4,
    status: "in_review",
    aiSummary: "AI已生成4个成长片段",
  },
  {
    id: "sess-004",
    student: "小然",
    studentId: "stu-004",
    date: "2026-05-20",
    type: "训练",
    clipCount: 2,
    status: "draft",
    aiSummary: "AI已生成2个成长片段",
  },
];

export const mockOrgStats = {
  totalStudents: 24,
  activeStudents: 20,
  reportsThisMonth: 18,
  reportOpenRate: 0.78,
  videoPlayRate: 0.62,
  shareRate: 0.31,
  conversionLeads: 4,
  renewalLeads: 6,
};

export const mockLeads = [
  {
    id: "lead-001",
    student: "蒋皓博",
    studentId: "stu-001",
    type: "private_training",
    typeLabel: "私教推荐",
    reason: "连续3次出现「突破终结不稳定」，家长已播放相关片段5次",
    relatedReport: "蒋皓博 5月24日比赛成长报告",
    suggestedMessage: "王教练，根据蒋皓博最近几场比赛的成长数据，他在突破后的左手终结上有很大提升空间。我们有专门针对这个技术的1对1私教课，非常适合他现在的阶段，你觉得可以安排一节试试吗？",
    status: "new",
    priority: "high",
    coachConfirmed: true,
  },
  {
    id: "lead-002",
    student: "季禹澄",
    studentId: "stu-002",
    type: "renewal",
    typeLabel: "续费线索",
    reason: "本月报告打开4次，家长分享过1次，成长趋势明显向好",
    relatedReport: "季禹澄 5月24日比赛成长报告",
    suggestedMessage: "您好！季禹澄这个月进步非常明显，在防守意识和传球选择上都有很大提升。我们下一期U10提高班正在开放续费，以他现在的状态非常适合继续这个班级的训练。",
    status: "contacted",
    priority: "medium",
    coachConfirmed: true,
  },
  {
    id: "lead-003",
    student: "小杰",
    studentId: "stu-003",
    type: "renewal",
    typeLabel: "续费线索",
    reason: "出勤率100%，训练投入度高，家长互动积极",
    relatedReport: "5月22日训练成长记录",
    suggestedMessage: "家长好！小杰这学期出勤率达到100%，每次训练都非常投入，成长证据积累非常扎实。我们非常希望他继续这个阶段的训练，续费详情方便这两天聊一下吗？",
    status: "new",
    priority: "medium",
    coachConfirmed: false,
  },
  {
    id: "lead-004",
    student: "小然",
    studentId: "stu-004",
    type: "care",
    typeLabel: "关怀跟进",
    reason: "近两周出勤率下降，家长未查看最新报告",
    relatedReport: "5月20日训练成长记录",
    suggestedMessage: "家长您好，我们注意到小然最近两周有几次未能参加训练，他之前的成长势头很好，不知道最近有什么需要我们配合的吗？",
    status: "new",
    priority: "low",
    coachConfirmed: false,
  },
];

export const mockStudentCards = [
  {
    id: "stu-001",
    name: "蒋皓博",
    namePinyin: "JIANG HAOBO",
    number: "3",
    position: "GUARD",
    photo: "/students/jiang-haob0.jpg",
    prebuiltCard: null,
  },
  {
    id: "stu-002",
    name: "季禹澄",
    namePinyin: "JI YUCHENG",
    number: "94",
    position: "GUARD",
    photo: null,
    prebuiltCard: "/students/ji-yucheng-card.jpg",
  },
];

export const mockStudentList = [
  { id: "stu-001", name: "蒋皓博", age: 10, class: "U10提高班", reportCount: 8, openRate: 0.9, lastActive: "2026-05-24", growth: "up" },
  { id: "stu-002", name: "季禹澄", age: 10, class: "U10提高班", reportCount: 7, openRate: 0.85, lastActive: "2026-05-24", growth: "up" },
  { id: "stu-003", name: "小杰", age: 11, class: "U10提高班", reportCount: 9, openRate: 0.78, lastActive: "2026-05-22", growth: "stable" },
  { id: "stu-004", name: "小然", age: 10, class: "U10提高班", reportCount: 6, openRate: 0.5, lastActive: "2026-05-10", growth: "down" },
  { id: "stu-005", name: "浩然", age: 11, class: "U10提高班", reportCount: 7, openRate: 0.72, lastActive: "2026-05-20", growth: "stable" },
  { id: "stu-006", name: "子轩", age: 9, class: "U8基础班", reportCount: 5, openRate: 0.80, lastActive: "2026-05-18", growth: "up" },
];

export const dimensionColors: Record<string, string> = {
  "技术成长": "#F97316",
  "战术认知": "#8B5CF6",
  "比赛状态": "#3B82F6",
  "心理成长": "#EF4444",
  "团队协作": "#10B981",
  "训练习惯": "#F59E0B",
};
